title: Raport rynku domen na rok 2024
description: Jak zmieniał się rynek domen w ostatniej dekadzie? Jak zmieni się rynek do roku 2030?
mermaid:
  src: "mermaid.js"
plugins:
  - "jekyll-github-metadata"  
  - "jekyll-readme-index"
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
